plugins {
    id 'io.micronaut.build.internal.test-resources-module'
}

description = """
Provides support for resolving test properties via a server.
The server is responsible for returning the list of properties it can supply,
and provide their value on demand.
"""

dependencies {
    api(mn.micronaut.http)
    api(projects.micronautTestResourcesCore)
    compileOnly(mn.micronaut.context)
    implementation(projects.micronautTestResourcesCodec)
    testImplementation(platform(libs.boms.netty)) {
        because("Bump Netty patch version for GHSA-v8h7-rr48-vmmv")
    }
    testImplementation(mn.micronaut.http.server.netty)
    testRuntimeOnly(mn.micronaut.http.server.netty)
}
