OAuth2 support currently provisions https://www.keycloak.org/[Keycloak] for a Micronaut Security OAuth2 client named `keycloak`.

When `micronaut-security-oauth2` is on the application classpath, Test Resources can resolve these properties automatically:

- `micronaut.security.oauth2.clients.keycloak.client-id`
- `micronaut.security.oauth2.clients.keycloak.client-secret`
- `micronaut.security.oauth2.clients.keycloak.openid.issuer`

Micronaut Security discovers the JWKS URI from the issuer's OpenID Provider metadata. Test Resources does not resolve `micronaut.security.token.jwt.signatures.jwks.keycloak.url`, because it would register a second JWKS configuration with the same name. If a test needs the direct Keycloak JWKS URL, derive `/protocol/openid-connect/certs` from the issuer.

The default image (`{default-image-keycloak}`) can be overwritten by setting the `test-resources.containers.keycloak.image-name` property.
The default image tag can be overwritten by setting the `test-resources.containers.keycloak.image-tag` property.

You can customize the imported realm and client credentials with:

[configuration]
----
test-resources:
  containers:
    keycloak:
      realm: 'micronaut'
      client-id: 'my-client'
      client-secret: 'my-secret'
----
