== Databases

Micronaut Test Resources provides support for the following databases:

[cols="2,1,1,1,1"]
|===
|Database | JDBC | R2DBC | Database identifier | Default image

| https://www.h2database.com/html/main.html[H2] | Yes | No | `h2` | n/a
| https://mariadb.org/[MariaDB] | Yes | Yes | `mariadb` | `{default-image-mariadb}`
| https://www.mysql.com/[MySQL] | Yes | Yes | `mysql` | `{default-image-mysql-community}`
| https://www.oracle.com/database/technologies/appdev/xe.html[Oracle Database XE] | Yes | Yes | `oracle-xe` | `{default-image-oracle-xe}`
| https://www.oracle.com/database/free/[Oracle Database Free] | Yes | Yes | `oracle` | `{default-image-oracle-free}`
| https://www.postgresql.org/[PostgreSQL] | Yes | Yes | `postgres` | `{default-image-postgres}`
| https://www.microsoft.com/sql-server[Microsoft SQL Server] | Yes | Yes | `mssql` | `{default-image-mssql}`

|===

Most databases are supplied via a https://www.testcontainers.com/[Testcontainers] container.
H2 is containerless and starts a loopback-only in-memory TCP server for the lifetime of the test-resources process.
Shared or remote H2 test resources are not supported at this time, so the H2 resolver stays disabled when `micronaut.test.resources.server.uri` is configured.
It is possible to override the default image of the container by setting the following property in your application configuration:

- `test-resources.containers.[db-type].image-name`

For example, you can override the default image of the container for the `MariaDB` database by setting the following property:

[configuration]
----
test-resources:
  containers:
    mariadb:
      image-name: mariadb:10.3
----

The `db-type` property value can be found in the table above.

Similarly, you can use the following properties to override some default test resources parameters:

- `test-resources.containers.[db-type].db-name`: overrides the default test database name
- `test-resources.containers.[db-type].username`: overrides the default test user
- `test-resources.containers.[db-type].password`: overrides the default test password
- `test-resources.containers.[db-type].init-script-path`: a path to a SQL file on classpath, which will be executed at container startup

[NOTE]
====
Using the Microsoft SQL Server container will require you to accept its license. In order to do this, you must set the `test-resources.containers.mssql.accept-license` property to true:

[configuration]
----
test-resources:
  containers:
    mssql:
      accept-license: true
----

====

TIP: See the guide for https://guides.micronaut.io/latest/replace-h2-with-real-database-for-testing.html[Replace H2 with a Real Database for Testing] to learn more.
