== Databases

Micronaut Test Resources provides support for the following databases:

[cols="2,1,1,1,1"]
|===
|Database | JDBC | R2DBC | Database identifier | Default image

| https://mariadb.org/[MariaDB] | Yes | Yes | mariadb | mariadb
| https://www.mysql.com/[MySQL] | Yes | Yes | mysql | mysql
| https://www.oracle.com/fr/database/technologies/appdev/xe.html[Oracle Express Edition] | Yes | Yes | oracle-xe | gvenzl/oracle-xe:slim-faststart
| https://www.postgresql.org/[PostgreSQL] | Yes | Yes | postgres | postgres
| https://www.microsoft.com/sql-server[Microsoft SQL Server] | Yes | Yes | mssql | mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04

|===

Databases are supplied via a https://www.testcontainers.com/[Testcontainers] container.
It is possible to override the default image of the container by setting the following property in your application configuration:

- `test-resources.containers.[db-type].image-name`

For example, you can override the default image of the container for the `MariaDB` database by setting the following property:

.application.yml
[source,yaml]
----
test-resources:
  containers:
    mariadb:
      image-name: mariadb:10.3
----

The `db-type` property value can be found in the table above.

[NOTE]
====
Using the Microsoft SQL Server container will require you to accept its license. In order to do this, you must set the `test-resources.containers.mssql.accept-license` property to true:
```yaml
test-resources:
  containers:
    mssql:
      accept-license: true
```
====
