Kafka support will automatically start a https://kafka.apache.org[Kafka container] and provide the value of the `kafka.bootstrap.servers` property.

The default image (`{default-image-kafka}`) can be overwritten by setting the `test-resources.containers.kafka.image-name` property.

Kafka topics are only provisioned when `test-resources.containers.kafka.topics` is configured. When set, test resources creates any missing topics before returning `kafka.bootstrap.servers`.

The optional `test-resources.containers.kafka.partitions` property applies the same partition count to every configured topic and defaults to `1`.

NOTE: Topic replication is fixed to `1` because the Kafka test resource starts a single-broker container. This feature is intended for test-time broker preparation, not general Kafka administration.

NOTE: When a cached Kafka broker is reused inside the same test-resources scope, configured topics must agree on the partition count. If a topic already exists with a different partition count, resolution fails with a clear error instead of mutating the existing topic.

[configuration]
----
test-resources:
  containers:
    kafka:
      topics:
        - orders
        - shipments
      partitions: 3
----

TIP: See the guide for https://guides.micronaut.io/latest/testing-micronaut-kafka-listener-using-testcontainers.html[Testing Kafka Listener using Testcontainers with the Micronaut Framework] to learn more.


https://docs.confluent.io/platform/current/kafka-metadata/kraft.html#kraft-overview[Kraft Mode] is supported via the `test-resources.containers.kafka.kraft` property.

[configuration]
----
test-resources:
  containers:
    kafka:
      kraft: true
----

NOTE: This switches to the https://docs.confluent.io/platform/current/installation/docker/image-reference.html#ak-images[confluent-local] Docker image with https://java.testcontainers.org/modules/kafka/#using-kraft-mode[TestContainer Kraft Support]
