== Databases

Micronaut Test Resources provides support for the following relational databases:

[cols="2,1,1,1"]
|===
|Database | JDBC | R2DBC | Database identifier

| https://mariadb.org/[MariaDB] | Yes | Yes | mariadb
| https://www.mysql.com/[MySQL] | Yes | Yes | mysql
| https://www.oracle.com/fr/database/technologies/appdev/xe.html[Oracle Express Edition] | Yes | Yes | oracle-xe
| https://www.postgresql.org/[PostgreSQL] | Yes | Yes | postgres
| https://www.microsoft.com/sql-server[Microsoft SQL Server] | Yes | Yes | mssql

|===

Databases are supplied via a https://www.testcontainers.com/[Testcontainers] container.
It is possible to override the default image of the container by setting the following property in your application configuration:

- `test-resources.containers.[db-type].image-name`

For example, you can override the default image of the container for the `MariaDB` database by setting the following property:

[configuration]
----
test-resources:
  containers:
    mariadb:
      image-name: mariadb:10.3
----

The `db-type` property value can be found in the table above.

[NOTE]
====
Using the Microsoft SQL Server container will require you to accept its license. In order to do this, you must set the `test-resources.containers.mssql.accept-license` property to true:

[configuration]
----
test-resources:
  containers:
    mssql:
      accept-license: true
----

====

For a complete list configurable properties refer to the https://micronaut-projects.github.io/micronaut-test-resources/latest/guide/configurationreference.html#io.micronaut.testresources.testcontainers.TestContainersConfiguration[Configuration Reference for Test Containers].

[NOTE]
====
The initial image download of some database images can take some time depending the size and speed of your internet connection. In this case you may receive a `ReadTimeoutException`, to resolve this you should configrue the  `clientTimeout` in either the https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_configuring_the_test_resources_plugin[Gradle] or https://micronaut-projects.github.io/micronaut-maven-plugin/latest/start-testresources-service-mojo.html#clienttimeout[Maven].

In addition, sometimes containers may timeout starting up which requires configuring the startup timeout, for example the following extends the startup time for the `oracle` container image: 

[configuration]
----
test-resources:
  containers:
    oracle:
      startup-timeout: 300s
----
====
