Micronaut Test Resources are integrated via build plugins.

The recommended approach to get started is to use https://micronaut.io/launch[Micronaut Launch] and select the `test-resources` feature.

If you want to integrate it manually, for Gradle you can use the `micronaut-test-resources` plugin.
Use the same Micronaut Gradle plugin version for `io.micronaut.test-resources` and `io.micronaut.application`:

.Gradle
[source,groovy,subs="verbatim,attributes"]
----
plugins {
    id 'io.micronaut.test-resources' version '<micronaut-gradle-plugin-version>'
    id 'io.micronaut.application' version '<micronaut-gradle-plugin-version>'
}
----

Please refer to the https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#test-resources[Gradle plugin's Test Resources documentation] for more information about configuring the test resources plugin.

In the case of Maven, you can enable test resources support simply by setting the property `micronaut.test.resources.enabled` (either in your
POM or via the command-line).

When a test resources client is on the application runtime classpath, you can disable runtime resolution without changing test behavior by setting `micronaut.test.resources.enabled=false` as a system property for the application run, or `test-resources.enabled=false` in application configuration.

Please refer to the https://micronaut-projects.github.io/micronaut-maven-plugin/latest/examples/test-resources.html[Maven plugin's Test Resources documentation] for more information about configuring the test resources plugin.
