plugins {
    id 'io.micronaut.build.internal.test-resources-base'
    id "io.micronaut.build.internal.base-module"
}

dependencies {
    // These dependencies are compileOnly because they
    // are going to run in the server process which is
    // a fat jar, so they must not leak to the classpath
    annotationProcessor mn.micronaut.inject.java
    compileOnly mn.micronaut.inject
    testImplementation(mnTest.micronaut.test.spock) {
        // temporary fix because Micronaut Test not yet compiled with Spock groovy 5
        exclude group: 'org.spockframewoek'
    }
    testImplementation(libs.spock)
    testRuntimeOnly mnSerde.micronaut.serde.jackson
    testRuntimeOnly mn.snakeyaml

    constraints {
        implementation("com.fasterxml.jackson.core:jackson-databind:2.21.5") {
            because "fixes jackson-databind vulnerabilities reported by the PR vulnerability audit"
        }
    }
}

configurations.all {
    resolutionStrategy.preferProjectModules()
}

tasks.named("japiCmp") {
    newClasspath.from(configurations.compileClasspath)
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.testresources:micronaut-test-resources-core"
    }
    binaryCompatibility {
        // preparing major version
        enabledAfter("4.0.0")
    }
}
