plugins {
    id "io.micronaut.build.internal.parent"
}

pluginManager.apply(io.micronaut.build.catalogs.MicronautVersionCatalogUpdatePlugin)

tasks.withType(io.micronaut.build.catalogs.tasks.VersionCatalogUpdate).configureEach {
    outputDirectory = file("gradle")
    failWhenNoVersionFound = false
}

tasks.named("publishGuide") {
    properties['micronautVersion'] = micronautVersion
}

repositories {
    mavenCentral()
//    maven {
//        url "https://s01.oss.sonatype.org/content/repositories/snapshots"
//    }
}

def rootSonarExtension = extensions.findByName("sonar")
if (rootSonarExtension != null) {
    rootSonarExtension.skipProject = true
}

project(":micronaut-test-resources-bom") {
    def bomSonarExtension = extensions.findByName("sonar")
    if (bomSonarExtension != null) {
        bomSonarExtension.skipProject = true
    }
}
