plugins {
    id 'io.micronaut.build.internal.testcontainers-module'
    id 'io.micronaut.build.internal.kafka-testing'
}

description = """
Provides support for launching a Kafka test container.
"""

dependencies {
    compileOnly(projects.micronautTestResourcesCompose)
    implementation(libs.managed.testcontainers.kafka)
    implementation(mnKafka.kafka.clients)

    testImplementation(mnReactor.micronaut.reactor)
    testImplementation(mnKafka.micronaut.kafka)
}
