plugins {
    id 'io.micronaut.build.internal.test-resources-module'
}

description = """
Adds a control panel to the test resources server
"""

dependencies {
    implementation(mnControlPanel.micronaut.control.panel.ui)
    implementation(libs.managed.testcontainers.core)
    implementation(projects.micronautTestResourcesTestcontainers)
    implementation(projects.micronautTestResourcesEmbedded)
    implementation(projects.micronautTestResourcesServer)
    runtimeOnly(mn.micronaut.management)
    constraints {
        implementation("ch.qos.logback:logback-core:1.5.25") {
            because "CVE:  CVE-2025-11226"
        }
    }
}

micronautBuild {
    binaryCompatibility {
        enabledAfter '2.2.0'
    }
}
