plugins {
    id 'io.micronaut.build.internal.test-resources-module'
}

description = """
Provides support for launching an Infinispan test container.
"""

dependencies {
    api(projects.micronautTestResourcesCore)
    api(projects.micronautTestResourcesTestcontainers)
    api("org.infinispan:infinispan-server-testdriver-core:${mnCache.versions.infinispan.get()}")

    testImplementation(projects.micronautTestResourcesEmbedded)
    testImplementation(testFixtures(projects.micronautTestResourcesTestcontainers))
    testImplementation(mnCache.micronaut.cache.infinispan)
}
