plugins {
    id 'io.micronaut.build.internal.test-resources-module'
}

description = """
Provides support for resolving test resources from Docker Compose services.
"""

dependencies {
    api(project(':micronaut-test-resources-core'))

    runtimeOnly(project(':micronaut-test-resources-azure'))
    runtimeOnly(project(':micronaut-test-resources-couchbase'))
    runtimeOnly(project(':micronaut-test-resources-hashicorp-consul'))
    runtimeOnly(project(':micronaut-test-resources-hashicorp-vault'))
    runtimeOnly(project(':micronaut-test-resources-hazelcast'))
    runtimeOnly(project(':micronaut-test-resources-hibernate-reactive-mariadb'))
    runtimeOnly(project(':micronaut-test-resources-hibernate-reactive-mssql'))
    runtimeOnly(project(':micronaut-test-resources-hibernate-reactive-mysql'))
    runtimeOnly(project(':micronaut-test-resources-hibernate-reactive-oracle-free'))
    runtimeOnly(project(':micronaut-test-resources-hibernate-reactive-oracle-xe'))
    runtimeOnly(project(':micronaut-test-resources-hibernate-reactive-postgresql'))
    runtimeOnly(project(':micronaut-test-resources-hivemq'))
    runtimeOnly(project(':micronaut-test-resources-infinispan'))
    runtimeOnly(project(':micronaut-test-resources-jdbc-mariadb'))
    runtimeOnly(project(':micronaut-test-resources-jdbc-mssql'))
    runtimeOnly(project(':micronaut-test-resources-jdbc-mysql'))
    runtimeOnly(project(':micronaut-test-resources-jdbc-oracle-free'))
    runtimeOnly(project(':micronaut-test-resources-jdbc-oracle-xe'))
    runtimeOnly(project(':micronaut-test-resources-jdbc-postgresql'))
    runtimeOnly(project(':micronaut-test-resources-kafka'))
    runtimeOnly(project(':micronaut-test-resources-localstack-core'))
    runtimeOnly(project(':micronaut-test-resources-localstack-dynamodb'))
    runtimeOnly(project(':micronaut-test-resources-localstack-s3'))
    runtimeOnly(project(':micronaut-test-resources-localstack-sns'))
    runtimeOnly(project(':micronaut-test-resources-localstack-sqs'))
    runtimeOnly(project(':micronaut-test-resources-minio'))
    runtimeOnly(project(':micronaut-test-resources-mongodb'))
    runtimeOnly(project(':micronaut-test-resources-neo4j'))
    runtimeOnly(project(':micronaut-test-resources-oauth2'))
    runtimeOnly(project(':micronaut-test-resources-opensearch'))
    runtimeOnly(project(':micronaut-test-resources-pulsar'))
    runtimeOnly(project(':micronaut-test-resources-r2dbc-mariadb'))
    runtimeOnly(project(':micronaut-test-resources-r2dbc-mssql'))
    runtimeOnly(project(':micronaut-test-resources-r2dbc-mysql'))
    runtimeOnly(project(':micronaut-test-resources-r2dbc-oracle-free'))
    runtimeOnly(project(':micronaut-test-resources-r2dbc-oracle-xe'))
    runtimeOnly(project(':micronaut-test-resources-r2dbc-postgresql'))
    runtimeOnly(project(':micronaut-test-resources-rabbitmq'))
    runtimeOnly(project(':micronaut-test-resources-redis'))
    runtimeOnly(project(':micronaut-test-resources-seaweedfs'))
    runtimeOnly(project(':micronaut-test-resources-solr'))
    runtimeOnly(project(':micronaut-test-resources-wiremock'))
}
