plugins {
    id 'io.micronaut.build.internal.testcontainers-module'
}

description = """
Provides support for launching an Azurite test container.
"""

dependencies {
    compileOnly(projects.micronautTestResourcesCompose)
    testImplementation(platform(libs.azure.sdk.bom))
    testImplementation(libs.azure.storage.blob)
}
