plugins {
    id 'io.micronaut.build.internal.testcontainers-module'
}

description = """
Provides support for launching a Keycloak test container for OAuth2 tests.
"""

dependencies {
    compileOnly(projects.micronautTestResourcesCompose)
    testImplementation(testFixtures(projects.micronautTestResourcesTestcontainers))
    testImplementation(mn.micronaut.jackson.databind)
    testImplementation(mnSecurity.micronaut.security.oauth2)
    testRuntimeOnly(mnSerde.micronaut.serde.jackson)
}
