plugins {
    id 'io.micronaut.build.internal.test-resources-module'
}

description = """
Provides support for launching a Redis test container.
"""

dependencies {
    api(projects.micronautTestResourcesCore)
    api(projects.micronautTestResourcesTestcontainers)
    api(libs.managed.testcontainers.redis)
    compileOnly(projects.micronautTestResourcesCompose)

    testImplementation(projects.micronautTestResourcesEmbedded)
    testImplementation(testFixtures(projects.micronautTestResourcesTestcontainers))
    testImplementation(mnRedis.micronaut.redis.lettuce)

    constraints {
        implementation("com.fasterxml.jackson.core:jackson-core:2.21.3")
    }
}
