plugins {
    id 'io.micronaut.build.internal.server-module'
    // server uses kafka in tests
    id 'io.micronaut.build.internal.kafka-testing'
    alias(libs.plugins.micronaut.miniapp)
    alias(libs.plugins.micronaut.aot)
    id('java-test-fixtures')
}

description = """
A lightweight server which runs a VM responsible for hosting
test resource resolvers.
This server must be used in conjunction with the test resources
client.
"""

dependencies {
    implementation(mn.micronaut.http.server.netty)
    implementation(mn.reactor)
    implementation(projects.micronautTestResourcesCodec)
    implementation(projects.micronautTestResourcesCore)
    implementation(projects.micronautTestResourcesEmbedded)
    implementation(projects.micronautTestResourcesTestcontainers)
    runtimeOnly(mnLogging.logback.classic)
    runtimeOnly(mnSerde.micronaut.serde.support)
    runtimeOnly(mn.snakeyaml)

    constraints {
        implementation(libs.netty.codec.http) {
            because "fixes GHSA-hvcg-qmg6-jm4c from Micronaut HTTP Netty transitive dependencies"
        }
        implementation(libs.netty.codec.http2) {
            because "fixes GHSA-563q-j3cm-6jxm, GHSA-5x3r-wrvg-rp6q, and GHSA-c2gf-v879-257j from Micronaut HTTP Netty transitive dependencies"
        }
        implementation(libs.netty.handler) {
            because "fixes GHSA-3qp7-7mw8-wx86, GHSA-c653-97m9-rcg9, and GHSA-x4gw-5cx5-pgmh from Micronaut HTTP Netty transitive dependencies"
        }
        implementation(libs.netty.resolver.dns) {
            because "fixes GHSA-5pvg-856g-cp85, GHSA-676x-f7gg-47vc, and GHSA-xmv7-r254-6q78 from Micronaut HTTP Netty transitive dependencies"
        }
        implementation(libs.netty.transport.native.epoll) {
            because "fixes GHSA-w573-9ffj-6ff9 from Micronaut HTTP Netty transitive dependencies"
        }
    }

    testFixturesImplementation(projects.micronautTestResourcesCore)
    testFixturesImplementation(projects.micronautTestResourcesTestcontainers)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mnLogging.logback.classic)
    testImplementation(projects.micronautTestResourcesClient)
    // TODO: MN5 Requires Micronaut Kafka release
//    testRuntimeOnly(projects.micronautTestResourcesKafka)

    // For logback conversion
    aotPlugins(mnLogging.logback.classic)
    aotPlugins(libs.jansi)
    aotPlugins(testFixtures(projects.micronautTestResourcesServer))

    // In order to support the control panel at runtime
    aotApplication projects.micronautTestResourcesControlPanel
}

application {
    mainClass = "io.micronaut.testresources.server.TestResourcesService"
}

micronaut {
    version = libs.versions.micronaut.platform.get()
    aot {
        version = libs.versions.micronaut.aot.get()
        cacheEnvironment.set(true)
        optimizeServiceLoading.set(false)
        optimizeClassLoading.set(true)
        convertYamlToJava.set(false)
        precomputeOperations.set(true)
        deduceEnvironment.set(true)
        // We have to set it to false because the generated
        // Java configuration is somehow wrong and generates
        // duplicate log lines
        replaceLogbackXml.set(false)
        configFile.set(file("src/aot/aot.properties"))
    }
}

micronautBuild {
    binaryCompatibility {
        // binary checks work on the wrong jar file
        enabled = false
    }
}

tasks.named("test") {
    systemProperty("test.resources.server.runtime.classpath", sourceSets.main.runtimeClasspath.asPath)
}
