plugins {
    id 'io.micronaut.build.internal.jdbc-module'
}

description = """
Provides support for launching a PostgreSQL test container.
"""

dependencies {
    compileOnly(project(':micronaut-test-resources-compose'))
    implementation(libs.managed.testcontainers.postgres)

    testRuntimeOnly(mnSql.postgresql)
}
